Resources:
  ExampleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      "AttributeDefinitions":
        - "AttributeName": "id"
          "AttributeType": "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false
      BillingMode: PAY_PER_REQUEST
      TableName: "LambdaExample"
# User
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "User"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
# Pantry
  PantryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Pantry"
      AttributeDefinitions:
        - AttributeName: "pantryItemId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pantryItemId"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Recipe"
      AttributeDefinitions:
        - AttributeName: "recipeId"
          AttributeType: "S"
      "KeySchema":
        - "AttributeName": "id"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQUEST
