Resources:
#  ExampleTable:
#    Type: AWS::DynamoDB::Table
#    Properties:
#      TableName: "LambdaExample"
#      "AttributeDefinitions":
#        - "AttributeName": "id"
#          "AttributeType": "S"
#      "KeySchema":
#        - "AttributeName": "id"
#          "KeyType": "HASH"
#      PointInTimeRecoverySpecification:
#        PointInTimeRecoveryEnabled: false
#      BillingMode: PAY_PER_REQUEST
# User
  UserTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "User"
      AttributeDefinitions:
        - AttributeName: "userId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQ
# Pantry
  PantryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Pantry"
      AttributeDefinitions:
        - AttributeName: "pantryItemId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "pantryItemId"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQ
# Recipe
  RecipeTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "Recipe"
      AttributeDefinitions:
        - AttributeName: "recipeId"
          AttributeType: "S"
      "KeySchema":
        - "AttributeName": "recipeId"
          "KeyType": "HASH"
      BillingMode: PAY_PER_REQ
