@startuml

!theme reddress-darkred
scale 1
skinparam classFontSize 12
skinparam titleFontSize 20

title
<u>Term 4 Capstone</u>
end title

class LibraryBook {
+ isbn: String
+ subjectList: String
  + LibraryBook(String title, String author)
  + setBookInfo(responseString: String): void
  + toString(): String
  + getIsbn(): String
  + setIsbn(isbn: String): void
  + getSubjectList(): String
  + setSubjectList(subjectList: String): void
}

class Book {
    + Book()
    + Book(title: String, author: String)
    + toString(): String
    + setBookInfo(responseString: String): void
    + getTitle(): String
    + setTitle(title: String): void
    + getAuthor(): String
    + setAuthor(author: String): void
}


class Logger {
- logFile: String
    - writer: PrintWriter
    - logger: Logger    + Logger()
    + getInstance(): Logger
    + logMessage(message: String): void
}


class DocumentDTO {
- subject: List<String>
    - person: List<String>
    - authorName: List<String>
    - isbn: List<String>
    - title: String    + getSubject(): List<String>
    + getAuthorName(): List<String>
    + getTitle(): String
    + getIsbn(): List<String>
}

    class BookRequestDTO {
    - numfoundexact: boolean
    - start: int
    - numfound: int
    - docs: ArrayList<DocumentDTO>    + getDocs(): ArrayList<DocumentDTO>
    + setDocs(docs: ArrayList<DocumentDTO>): void
    + getNumFound(): int
    + setNumFound(numfound: int): void
}


class BookRequestService {
- DEBUG: boolean
    + GET_URL: String
    + logger: Logger    + formatSearchString(requestString: String): String
    + formatResponseString(requestString: String, isbn: String, subjectList: ArrayList<String>): String
    + sendGetRequest(requestString: String): String
}

class Application {
  + convertResponseToLibraryBook(response: String): LibraryBook
  + returnBookList(response1: String, response2: String, response3: String, response4: String, response5: String): ArrayList<LibraryBook>
}

Application -- Logger

Application ..|> LibraryBook

Application ..|> BookRequestService

BookRequestService .. BookRequestDTO

Book <|.. LibraryBook

DocumentDTO *-- Logger

@enduml